# Generated by Django 2.1.5 on 2019-01-22 08:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20190117_1926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SnippetModel',
            new_name='Snippet',
        ),
    ]
