# Generated by Django 2.1.5 on 2019-05-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190122_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='code',
        ),
        migrations.AddField(
            model_name='snippet',
            name='md5',
            field=models.TextField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='sha1',
            field=models.TextField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='sha256',
            field=models.TextField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
